// Library Books - from PDF uploads
export const LIBRARY_BOOKS = [
  {
    id: 'library_1',
    title: 'The Richest Man in Babylon',
    author: 'George S. Clason',
    titleKey: 'book_richestManInBabylon',
    isLibrary: true,
    pdfFile: 'Book_1.pdf',
  },
  {
    id: 'library_2',
    title: 'Atomic Habits',
    author: 'James Clear',
    titleKey: 'book_atomicHabits',
    isLibrary: true,
    pdfFile: 'Book_2.pdf',
  },
  {
    id: 'library_3',
    title: 'Rich Dad Poor Dad',
    author: 'Robert T. Kiyosaki',
    titleKey: 'book_richDadPoorDad',
    isLibrary: true,
    pdfFile: 'Book_3.pdf',
  },
];

// Recommended Books - financial literacy
export const RECOMMENDED_BOOKS = [
  {
    id: 'recommended_1',
    title: 'The Intelligent Investor',
    author: 'Benjamin Graham',
    titleKey: 'book_intelligentInvestor',
    isLibrary: false,
  },
  {
    id: 'recommended_2',
    title: 'A Random Walk Down Wall Street',
    author: 'Burton G. Malkiel',
    titleKey: 'book_randomWallStreet',
    isLibrary: false,
  },
  {
    id: 'recommended_3',
    title: 'The Little Book of Common Sense Investing',
    author: 'John C. Bogle',
    titleKey: 'book_littleBookCommonSense',
    isLibrary: false,
  },
  {
    id: 'recommended_4',
    title: 'Money Master the Game',
    author: 'Tony Robbins',
    titleKey: 'book_moneyMasterGame',
    isLibrary: false,
  },
  {
    id: 'recommended_5',
    title: 'The Index Card',
    author: 'Helaine Olen & Harold Pollack',
    titleKey: 'book_indexCard',
    isLibrary: false,
  },
  {
    id: 'recommended_6',
    title: 'The Bogleheads\' Guide to Investing',
    author: 'Taylor Larson, Mel Lindauer & Michael LeBoeuf',
    titleKey: 'book_boggleheadsGuide',
    isLibrary: false,
  },
  {
    id: 'recommended_7',
    title: 'Think and Grow Rich',
    author: 'Napoleon Hill',
    titleKey: 'book_thinkGrowRich',
    isLibrary: false,
  },
  {
    id: 'recommended_8',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    titleKey: 'book_psychologyMoney',
    isLibrary: false,
  },
  {
    id: 'recommended_9',
    title: 'Your Money or Your Life',
    author: 'Vicki Robin & Joe Dominguez',
    titleKey: 'book_yourMoneyLife',
    isLibrary: false,
  },
  {
    id: 'recommended_10',
    title: 'The Simple Path to Wealth',
    author: 'JL Collins',
    titleKey: 'book_simplePathWealth',
    isLibrary: false,
  },
  {
    id: 'recommended_11',
    title: 'Beat the Market',
    author: 'Edward E. Jones',
    titleKey: 'book_beatMarket',
    isLibrary: false,
  },
  {
    id: 'recommended_12',
    title: 'Principles: Life and Work',
    author: 'Ray Dalio',
    titleKey: 'book_principlesLife',
    isLibrary: false,
  },
  {
    id: 'recommended_13',
    title: 'A Few Lessons for Investors',
    author: 'Warren Buffett',
    titleKey: 'book_fewLessonsInvestors',
    isLibrary: false,
  },
  {
    id: 'recommended_14',
    title: 'The Millionaire Next Door',
    author: 'Thomas J. Stanley & William D. Danko',
    titleKey: 'book_millionaireNextDoor',
    isLibrary: false,
  },
  {
    id: 'recommended_15',
    title: 'Early Retirement Extreme',
    author: 'Jacob Lund Fisker',
    titleKey: 'book_earlyRetirementExtreme',
    isLibrary: false,
  },
  {
    id: 'recommended_16',
    title: 'The Smartest Money Book You\'ll Ever Read',
    author: 'Daniel R. Solin',
    titleKey: 'book_smartestMoneyBook',
    isLibrary: false,
  },
  {
    id: 'recommended_17',
    title: 'Fooled by Randomness',
    author: 'Nassim Nicholas Taleb',
    titleKey: 'book_fooledRandomness',
    isLibrary: false,
  },
  {
    id: 'recommended_18',
    title: 'The Behavioral Investor',
    author: 'Daniel Crosby',
    titleKey: 'book_behavioralInvestor',
    isLibrary: false,
  },
];

export const ALL_BOOKS = [...LIBRARY_BOOKS, ...RECOMMENDED_BOOKS];